Formation/Models/Certification.cs
using System;
using System.Collections.Generic;

namespace Formation.Models.DataBase
{
    public partial class Certification
    {
        
    }
}

Formation/Models/DataBase/Certification.cs
using System;
using System.Collections.Generic;

namespace Formation.Models.DataBase
{
    public partial class Certification
    {
        public long CertificationId { get; set; }
        public DateTime StartDate { get; set; }
        public DateTime EndDate { get; set; }
        public long? LevelId { get; set; }
        public long? EvaluationId { get; set; }

        public virtual Evaluation? Evaluation { get; set; }
        public virtual Level? Level { get; set; }
    }
}

Formation/Models/Employee.cs
using System;
using System.Collections.Generic;

namespace Formation.Models.DataBase
{
    public partial class Employee
    {
        public string Identity
        {
            get
            {
                return FirstName + " " + LastName;
            }
        }
    }
}

Formation/Areas/Formation/Controllers/CertificationsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Formation.Models.DataBase;

namespace Formation.Areas.Formation.API
{
    [Area("Formation")]
    public class CertificationsController : Controller
    {
        private readonly FormationContext _context;

        public CertificationsController(FormationContext context)
        {
            _context = context;
        }

        // GET: Formation/Certifications
        public async Task<IActionResult> Index()
        {
            var formationContext = _context.Certifications.Include(c => c.Evaluation).Include(c => c.Level);
            return View(await formationContext.ToListAsync());
        }
                
        // GET: Formation/Certifications/Details/5
        public async Task<IActionResult> Details(long? id)
        {
            if (id == null || _context.Certifications == null)
            {
                return NotFound();
            }

            var certification = await _context.Certifications
                .Include(c => c.Evaluation)
                .ThenInclude(c => c.Sheet)
                .ThenInclude(s => s.Equipment)
                .Include(c => c.Level)
                .FirstOrDefaultAsync(m => m.CertificationId == id);
            if (certification == null)
            {
                return NotFound();
            }

            return View(certification);
        }

        // GET: Formation/Certifications/Create
        public async Task<IActionResult> Create(long id)
        {
            Evaluation eval = await _context
                .Evaluations
                .Include(ev => ev.Points)
                .FirstOrDefaultAsync(ev => ev.EvaluationId == id);

            if(eval == null) return NotFound();

            var level = await _context.Levels
                .Where(le => le.SheetOperations
                            .Where(so => so.SheetId == eval.SheetId
                                    && so.DateSaved.HasValue
                                    && so.SheetTypeOperation.Text != "Remove"
                                    && so.DateSaved == _context.SheetOperations
                                        .Where(sod => sod.SheetId == so.SheetId
                                            && so.PointId == sod.PointId)
                                        .Max(sod => sod.DateSaved))
                            .All(so => eval.Points.Contains(so.Point)))
                .OrderByDescending(le => le.Level1)
                .FirstOrDefaultAsync();

            Certification cert = new Certification
            {
                EvaluationId = id,
                Evaluation = eval,
                StartDate = DateTime.Now,
                EndDate = DateTime.Now.AddMonths(6),
                LevelId = level == null ? (await _context.Levels.FirstOrDefaultAsync(le => le.Level1 == _context.Levels.Min(le1 => le1.Level1))).LevelId : level.LevelId,
                Level = level == null ? await _context.Levels.FirstOrDefaultAsync(le => le.Level1 == _context.Levels.Min(le1 => le1.Level1)) : level
            };
            ViewData["EvaluationId"] = id;
            ViewData["LevelId"] = new SelectList(_context.Levels, "LevelId", "LevelName");
            return View(cert);
        }

        // POST: Formation/Certifications/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CertificationId,StartDate,EndDate,LevelId,EvaluationId")] Certification certification)
        {
            if (ModelState.IsValid)
            {
                Employee employee = (await _context.Evaluations.Include(e => e.Employee).FirstOrDefaultAsync(e => e.EvaluationId == certification.EvaluationId)).Employee;

                _context.Add(certification);
                await _context.SaveChangesAsync();
                return RedirectToAction("Details", "Employees", new { area = "HumanResources", id = employee.EmployeeId });
            }
            ViewData["EvaluationId"] = new SelectList(_context.Evaluations, "EvaluationId", "EvaluationId", certification.EvaluationId);
            ViewData["LevelId"] = new SelectList(_context.Levels, "LevelId", "LevelId", certification.LevelId);
            return View(certification);
        }

        // GET: Formation/Certifications/Edit/5
        public async Task<IActionResult> Edit(long? id)
        {
            if (id == null || _context.Certifications == null)
            {
                return NotFound();
            }

            var certification = await _context.Certifications.FindAsync(id);
            if (certification == null)
            {
                return NotFound();
            }
            ViewData["EvaluationId"] = new SelectList(_context.Evaluations, "EvaluationId", "EvaluationId", certification.EvaluationId);
            ViewData["LevelId"] = new SelectList(_context.Levels, "LevelId", "LevelId", certification.LevelId);
            return View(certification);
        }

        // POST: Formation/Certifications/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(long id, [Bind("CertificationId,StartDate,EndDate,LevelId,EvaluationId")] Certification certification)
        {
            if (id != certification.CertificationId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(certification);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CertificationExists(certification.CertificationId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["EvaluationId"] = new SelectList(_context.Evaluations, "EvaluationId", "EvaluationId", certification.EvaluationId);
            ViewData["LevelId"] = new SelectList(_context.Levels, "LevelId", "LevelId", certification.LevelId);
            return View(certification);
        }

        // GET: Formation/Certifications/Delete/5
        public async Task<IActionResult> Delete(long? id)
        {
            if (id == null || _context.Certifications == null)
            {
                return NotFound();
            }

            var certification = await _context.Certifications
                .Include(c => c.Evaluation)
                .Include(c => c.Level)
                .FirstOrDefaultAsync(m => m.CertificationId == id);
            if (certification == null)
            {
                return NotFound();
            }

            return View(certification);
        }

        // POST: Formation/Certifications/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(long id)
        {
            if (_context.Certifications == null)
            {
                return Problem("Entity set 'FormationContext.Certifications'  is null.");
            }
            var certification = await _context.Certifications.FindAsync(id);
            if (certification != null)
            {
                _context.Certifications.Remove(certification);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CertificationExists(long id)
        {
          return (_context.Certifications?.Any(e => e.CertificationId == id)).GetValueOrDefault();
        }
    }
}

Formation/Areas/HumanResources/Controllers/CertificationsController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Formation.Models.DataBase;
using Formation.Areas.HumanResources.Models;

namespace Formation.Areas.HumanResources.Controllers
{
    [Area("HumanResources")]
    public class CertificationsController : Controller
    {
        private readonly FormationContext _context;

        public CertificationsController(FormationContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> SkillMatrix()
        {
            SkillMatrixVM outputViewModel = new SkillMatrixVM
            {
                Employees = await _context.Employees.ToListAsync(),
                Equipments = await _context.Equipment.ToListAsync(),
                Certifications = await _context.Certifications
                    .Include(c => c.Evaluation).ThenInclude(e => e.Sheet)
                    .Include(c => c.Level)
                    .Where(ce => ce.StartDate == _context.Certifications.Where(cem => cem.Evaluation.EmployeeId == ce.Evaluation.EmployeeId && cem.Evaluation.SheetId == ce.Evaluation.SheetId).Max(cem => cem.StartDate))
                    .ToListAsync()
            };
            return View(outputViewModel);
        }

        private bool CertificationExists(long id)
        {
            return _context.Certifications.Any(e => e.CertificationId == id);
        }
    }
}

Formation/Areas/HumanResources/Controllers/EmployeesController.cs
#nullable disable
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Formation.Models.DataBase;

namespace Formation.Areas.HumanResources.Controllers
{
    [Area("HumanResources")]
    public class EmployeesController : Controller
    {
        private readonly FormationContext _context;

        public EmployeesController(FormationContext context)
        {
            _context = context;
        }

        // GET: HumanResources/Employees
        public async Task<IActionResult> Index()
        {
            return View(await _context.Employees.ToListAsync());
        }

        // GET: HumanResources/Employees/Details/5
        public async Task<IActionResult> Details(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var employee = await _context.Employees
                .FirstOrDefaultAsync(m => m.EmployeeId == id);
            if (employee == null)
            {
                return NotFound();
            }

            return View(employee);
        }

        public async Task<IActionResult> Evaluations(long? id)
        {
            if(id == null)
            {
                return NotFound();
            }

            var employee = await _context.Employees
                .FirstOrDefaultAsync(m => m.EmployeeId == id);
            if (employee == null)
            {
                return NotFound();
            }

            ViewData["Employee"] = employee;
            return PartialView(await _context.Evaluations.Where(e => e.EmployeeId == id).Include(e => e.EmployeeId1Navigation).Include(e => e.Sheet).ThenInclude(s => s.Equipment).Include(e => e.Certification).ThenInclude(c => c.Level).OrderByDescending(e => e.DateStartEval).ToListAsync());
        }

        public async Task<IActionResult> Certifications(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var employee = await _context.Employees
                .FirstOrDefaultAsync(m => m.EmployeeId == id);
            if (employee == null)
            {
                return NotFound();
            }

            ViewData["Employee"] = employee;
            return PartialView(await _context.Certifications.Where(c => c.Evaluation.EmployeeId == id).Include(c => c.Level).Include(c => c.Evaluation).ThenInclude(e => e.Sheet).ThenInclude(s => s.Equipment).OrderByDescending(e => e.StartDate).ToListAsync());
        }

        // GET: HumanResources/Employees/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: HumanResources/Employees/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("FirstName,LastName")] Employee employee)
        {
            if (ModelState.IsValid)
            {
                _context.Add(employee);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(employee);
        }

        // GET: HumanResources/Employees/Edit/5
        public async Task<IActionResult> Edit(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var employee = await _context.Employees.FindAsync(id);
            if (employee == null)
            {
                return NotFound();
            }
            return View(employee);
        }

        // POST: HumanResources/Employees/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(long id, [Bind("EmployeeId,FirstName,LastName")] Employee employee)
        {
            if (id != employee.EmployeeId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(employee);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EmployeeExists(employee.EmployeeId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(employee);
        }





        // GET: HumanResources/Employees/Enable/5
        public async Task<IActionResult> Enable(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var employee = await _context.Employees
                .FirstOrDefaultAsync(m => m.EmployeeId == id);
            if (employee == null)
            {
                return NotFound();
            }

            return View(employee);
        }

        // POST: HumanResources/Employees/Enable/5
        [HttpPost, ActionName("Enable")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EnableConfirmed(long id)
        {
            var employee = await _context.Employees.FindAsync(id);
            _context.Employees.Remove(employee);
            //await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }





        // GET: HumanResources/Employees/Disable/5
        public async Task<IActionResult> Disable(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var employee = await _context.Employees
                .FirstOrDefaultAsync(m => m.EmployeeId == id);
            if (employee == null)
            {
                return NotFound();
            }

            return View(employee);
        }

        // POST: HumanResources/Employees/Disable/5
        [HttpPost, ActionName("Disable")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DisableConfirmed(long id)
        {
            var employee = await _context.Employees.FindAsync(id);
            _context.Employees.Remove(employee);
            //await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool EmployeeExists(long id)
        {
            return _context.Employees.Any(e => e.EmployeeId == id);
        }
    }
}

Formation/Areas/HumanResources/Views/Employees/Certifications.cshtml
@model IEnumerable<Formation.Models.DataBase.Certification>

<table class="table table-sm table-striped table-hover table-dark">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.StartDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EndDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Level)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Evaluation.Sheet.Equipment)
            </th>
            <th class="text-center">
                @Html.DisplayNameFor(model => model.Evaluation)
            </th>
            <th>
                Certification
            </th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.StartDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EndDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Level.LevelId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Evaluation.Sheet.Equipment.Name)
            </td>
            <td class="text-center">
                <a asp-area="Formation" asp-controller="Evaluations" asp-action="Details" asp-route-id="@item.EvaluationId" class="btn btn-sm btn-icon btn-green"><i class="bi bi-eye"></i><span>See</span></a>
            </td>
            <td>
                <a asp-area="Formation" asp-controller="Certifications" asp-action="Details" asp-route-id="@item.CertificationId" class="btn btn-sm btn-icon btn-green"><i class="bi bi-eye"></i><span>See</span></a>
            </td>
        </tr>
}
    </tbody>
</table>

Formation/Areas/HumanResources/Views/Employees/Create.cshtml
@model Formation.Models.DataBase.Employee

@{
    ViewData["Title"] = "Create";
}

<div class="container">

    <h2 class="text-center">Create</h2>

    <h4 class="text-center">Employee</h4>
    <hr />
    <div class="row">
        <div class="d-flex justify-content-center">
            <div class="col-md-4 text-center">
                <form asp-action="Create">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group mb-2">
                        <label asp-for="FirstName" class="control-label"></label>
                        <input asp-for="FirstName" class="form-control" />
                        <span asp-validation-for="FirstName" class="text-danger"></span>
                    </div>
                    <div class="form-group mb-2">
                        <label asp-for="LastName" class="control-label"></label>
                        <input asp-for="LastName" class="form-control" />
                        <span asp-validation-for="LastName" class="text-danger"></span>
                    </div>
                    <div class="form-group mt-4 row">
                        <a asp-action="Index" class="btn btn-warning col-5">Back to List</a>
                        <input type="submit" value="Create" class="btn btn-primary col-5 offset-2" />
                    </div>
                </form>
            </div>
        </div>
    </div>

</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Formation/Areas/HumanResources/Views/Employees/Details.cshtml
@model Formation.Models.DataBase.Employee

@{
	ViewData["Title"] = "Details";
}

<div class="container">

	<h2 class="text-center">Details</h2>

	<h4 class="text-center">Employee</h4>
	<hr />
	<div class="row">
		<div class="d-flex justify-content-center mt-4">
			<ul class="nav nav-tabs nav-fill col-8  mb-3" id="pills-tab" role="tablist">
				<li class="nav-item" role="presentation">
				<button class="nav-link active" id="pills-information-tab" data-bs-toggle="pill" data-bs-target="#pills-information" type="button" role="tab" aria-controls="pills-information" aria-selected="true">Information</button>
			  </li>
			  <li class="nav-item" role="presentation">
				<button class="nav-link" id="pills-evaluations-tab" data-bs-toggle="pill" data-bs-target="#pills-evaluations" type="button" role="tab" aria-controls="pills-evaluations" aria-selected="false">Evaluations</button>
			  </li>
			  <li class="nav-item" role="presentation">
				<button class="nav-link" id="pills-certifications-tab" data-bs-toggle="pill" data-bs-target="#pills-certifications" type="button" role="tab" aria-controls="pills-certifications" aria-selected="false">Certifications</button>
			  </li>
			</ul>
		</div>
		<div class="tab-content" id="pills-tabContent">
			<div class="tab-pane fade show active row" id="pills-information" role="tabpanel" aria-labelledby="pills-information-tab">
				<div class="row d-flex justify-content-center">
					<div id="information" class="col-10">
						<div class="d-flex justify-content-center">
							<div class="col-md-4 text-center">

								<div class="form-group mb-2">
									<label asp-for="FirstName" class="control-label"></label>
									<input asp-for="FirstName" class="form-control" disabled="disabled"/>
								</div>
								<div class="form-group mb-2">
									<label asp-for="LastName" class="control-label"></label>
									<input asp-for="LastName" class="form-control" disabled="disabled"/>
								</div>

								<div class="form-group mt-4 mb-4 row d-flex justify-content-center">
									<a asp-action="Edit" asp-route-id="@Model?.EmployeeId" class="btn btn-blue col-6">Edit</a>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="tab-pane fade" id="pills-evaluations" role="tabpanel" aria-labelledby="pills-evaluations-tab">
				<div class="row d-flex justify-content-center">
					<div id="evaluations" class="col-10">

					</div>
				</div>
			</div>
			<div class="tab-pane fade" id="pills-certifications" role="tabpanel" aria-labelledby="pills-certifications-tab">
				<div class="row d-flex justify-content-center">
					<div id="certifications" class="table-responsive col-10">

					</div>
				</div>
			</div>
		</div>

		<div class="row d-flex justify-content-center mt-4">
			<div class="col-4">
				<div class="form-group mt-4 mb-4 row d-flex justify-content-center">
					<a asp-action="Index" class="btn btn-warning col-6">Back to List</a>
				</div>
			</div>
		</div>
		

	</div>

</div>



@section Scripts{
        <script type="text/javascript" src="~/js/site.js"></script>

        <script type="text/javascript" src="~/js/pages/details_employee.js"></script>


        <script type="text/javascript">
            $(document).ready(function () {

                var partialview = {};
                partialview.evalURL = '@Url.RouteUrl("defaultArea", new { controller = "Employees", area="HumanResources", action="Evaluations"})';
				partialview.certURL = '@Url.RouteUrl("defaultArea", new { controller = "Employees", area="HumanResources", action="Certifications"})';

                var detailsEmployee = new DetailsEmployee(@Model.EmployeeId, partialview.evalURL, partialview.certURL);

            });
    </script>
}

Formation/Areas/HumanResources/Views/Employees/Disable.cshtml
@model Formation.Models.DataBase.Employee

@{
    ViewData["Title"] = "Delete";
}

<div class="container">

    <h2 class="text-center">Delete</h2>

    <h4 class="text-center">Employee</h4>
    <hr />
    <div class="row">
        <div class="d-flex justify-content-center">
            <div class="col-md-4 text-center">

                <div class="form-group mb-2">
                    <label asp-for="FirstName" class="control-label"></label>
                    <input asp-for="FirstName" class="form-control" disabled/>
                </div>
                <div class="form-group mb-2">
                    <label asp-for="LastName" class="control-label"></label>
                    <input asp-for="LastName" class="form-control" disabled/>
                </div>
    
                <form asp-action="Delete">
                    <input type="hidden" asp-for="EmployeeId" />

                    <div class="form-group mt-4 row">
                        <a asp-action="Index" class="btn btn-warning col-5">Back to List</a>
                        <input type="submit" value="Delete" class="btn btn-danger col-5 offset-2" />
                    </div>
                </form>
                </div>
        </div>
    </div>

</div>

Formation/Areas/HumanResources/Views/Employees/Edit.cshtml
@model Formation.Models.DataBase.Employee

@{
    ViewData["Title"] = "Edit";
}

<div class="container">

    <h2 class="text-center">Edit</h2>

    <h4 class="text-center">Employee</h4>
    <hr />
    <div class="row">
        <div class="d-flex justify-content-center">
            <div class="col-md-4 text-center">
                <form asp-action="Edit">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <input type="hidden" asp-for="EmployeeId" />
                    <div class="form-group mb-2">
                        <label asp-for="FirstName" class="control-label"></label>
                        <input asp-for="FirstName" class="form-control" />
                        <span asp-validation-for="FirstName" class="text-danger"></span>
                    </div>
                    <div class="form-group mb-2">
                        <label asp-for="LastName" class="control-label"></label>
                        <input asp-for="LastName" class="form-control" />
                        <span asp-validation-for="LastName" class="text-danger"></span>
                    </div>
                    <div class="form-group mt-4 row">
                        <a asp-action="Index" class="btn btn-warning col-5">Back to List</a>
                        <input type="submit" value="Save" class="btn btn-blue col-5 offset-2" />
                    </div>
                </form>
            </div>
        </div>
    </div>

</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Formation/Areas/HumanResources/Views/Employees/Evaluations.cshtml
@using Formation.Models.DataBase
@model IEnumerable<Formation.Models.DataBase.Evaluation>
@{
    Employee employee = (Employee)ViewBag.Employee;
}

<div class="row">
    <p>
        <a class="btn btn-blue" asp-area="Formation" asp-controller="Evaluations" asp-action="Create" asp-route-id="@employee.EmployeeId"><i style="margin-right:5px;" class="bi bi-plus-circle"></i> Evaluation</a>
    </p>
</div>

<table class="table table-sm table-striped table-hover table-dark">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.DateStartEval)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DateEndEval)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EmployeeId1Navigation)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Sheet.Equipment.Name)
            </th>
            <th class="text-center">@Html.DisplayNameFor(model => model.Certification)</th>
            <th class="text-center">Evaluation</th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.DateStartEval)
            </td>
            <td>
                @if (item.DateEndEval.HasValue)
                {
                    @Html.DisplayFor(modelItem => item.DateEndEval)
                }
                else
                {
                    <text>En cours</text>   
                }
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EmployeeId1Navigation.Identity)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Sheet.Equipment.Name)
            </td>
            <td class="text-center">
                @if (item.DateEndEval.HasValue)
                {
                   if(item.Certification == null){
                        <a id="btn_cert" asp-action="Create" asp-controller="Certifications" asp-area="Formation" asp-route-id="@item.EvaluationId" class="btn btn-sm btn-ico btn-blue"><i class="bi bi-plus-circle"></i> Create </a>
                   }else{
                        <a asp-area="Formation" asp-controller="Certifications" asp-action="Details" asp-route-id="@item.Certification.CertificationId" class="btn btn-sm btn-icon btn-green"><i class="bi bi-eye"></i><span>See</span></a>
                   }        
                }
            </td>
            <td class="text-center">
                @if (!item.DateEndEval.HasValue)
                {
                        <a asp-area="Formation" asp-controller="Evaluations" asp-action="Edit" asp-route-id="@item.EvaluationId" class="btn btn-sm btn-icon btn-blue"><i class="bi bi-pencil"></i><span>Edit</span></a>
                }
                <a asp-area="Formation" asp-controller="Evaluations" asp-action="Details" asp-route-id="@item.EvaluationId" class="btn btn-sm btn-icon btn-green"><i class="bi bi-eye"></i><span>See</span></a>
            </td>
        </tr>
}
    </tbody>
</table>